### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AldridgeAA**
@NtaleShadik
@mariamiah
@SokoPaulSokool
@okellogabrielinnocent

First pull request from develop branch to master branch.

### CODE REVIEW

**Comment by okellogabrielinnocent** [comment]
Good work
Make your repo public and add reviewers as collaboraters

**Comment by mariamiah** [comment]
Great...add collaborators via settings

**Comment by SokoPaulSokool** [comment]
Kool work

**Comment by SokoPaulSokool** [comment]
Great work

**Comment by NtaleShadik** [comment]
Nice work!

**Comment by NtaleShadik** [comment]
Nice

**Comment by mariamiah** [comment]
Great

**Pull request merged**
